# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0002_auto_20160825_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitOrCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='budgettype',
            name='debit_or_credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_scheduler.DebitOrCredit'),
        ),
    ]
