# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0004_auto_20160825_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='habibmalik', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
