# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0005_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgettype',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='task_scheduler.User'),
            preserve_default=False,
        ),
    ]
